### ISSUE TITLE
npm install: pathspec '0.1.0' did not match any file(s) known to git

### ISSUE THREAD

**Issue by joshuaharley** [wingify/vwo-node-sdk#31]
When installing the latest version of this package, 1.31.0, the package fails to install the `vwo-sdk-log-messages` dependency complaining that the tag 0.1.0 does not exist. We've pinned to a prior version to keep working but I believe the dependency needs to be updated to use the tag `v0.1.0` instead.

Here are the relevant log entries during install:

```text
silly fetchPackageMetaData error for vwo-sdk-log-messages@git+https://github.com/wingify/vwo-sdk-log-messages.git#0.1.0 Command failed: git checkout 0.1.0
silly fetchPackageMetaData error: pathspec '0.1.0' did not match any file(s) known to git
...
verbose stack Error: Command failed: git checkout 0.1.0
verbose stack error: pathspec '0.1.0' did not match any file(s) known to git
verbose stack
verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
verbose stack     at ChildProcess.emit (events.js:198:13)
verbose stack     at maybeClose (internal/child_process.js:982:16)
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
verbose cwd /wamp/www/react
verbose Linux 5.10.76-linuxkit
verbose argv "/usr/bin/node" "/usr/bin/npm" "update"
verbose node v10.24.1
verbose npm  v6.14.12
error code 1
error Command failed: git checkout 0.1.0
error error: pathspec '0.1.0' did not match any file(s) known to git
```

**Comment by softvar** [comment]
Hey @joshuaharley ,

Can you try installing one more time?

This is not happening at our end. The build is also passing for all the Node versions - https://github.com/wingify/vwo-node-sdk/runs/4801537261?check_suite_focus=true

Can you please let us know whether you're using npm or yarn and which version? That would help us in replicating the issue at our end too. Thanks!

**Comment by softvar** [comment]
We use `yarn` and it wasn't failing. When we tried with `npm` it was replicable. Thanks for reporting this.

We have fixed it in `v1.31.1`. Please take the latest pull and let us know if it works for you now. Sorry for the trouble.
